// Run manually when adding icons: node scripts/vendor-fonts.mjs. Builds need no network.
import fs from 'node:fs/promises';
import path from 'node:path';
import ts from 'typescript';

const root = path.resolve(import.meta.dirname, '..');
const names = new Set();
const collect = node => {
  if (ts.isStringLiteralLike(node) && /^[a-z][a-z0-9_]*$/.test(node.text)) names.add(node.text);
  if (ts.isJsxText(node) && /^[a-z][a-z0-9_]*$/.test(node.text.trim())) names.add(node.text.trim());
  ts.forEachChild(node, collect);
};
async function scan(directory) {
  for (const entry of await fs.readdir(directory, { withFileTypes: true })) {
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) await scan(file);
    else if (/\.tsx?$/.test(file)) {
      const source = ts.createSourceFile(file, await fs.readFile(file, 'utf8'), ts.ScriptTarget.Latest, true);
      const visit = node => {
        if (ts.isJsxElement(node) && node.openingElement.attributes.getText(source).includes('material-symbols-outlined')) node.children.forEach(collect);
        if (ts.isPropertyAssignment(node) && node.name.getText(source) === 'icon') collect(node.initializer);
        if (ts.isVariableDeclaration(node) && node.name.getText(source) === 'icons' && node.initializer) collect(node.initializer);
        ts.forEachChild(node, visit);
      };
      visit(source);
    }
  }
}
async function get(url) {
  const response = await fetch(url, { headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36' }, signal: AbortSignal.timeout(30_000) });
  if (!response.ok) throw new Error(`Font request failed (${response.status}): ${url}`);
  return response;
}
await scan(path.join(root, 'src'));
const iconNames = [...names].sort();
const output = path.join(root, 'public', 'fonts');
await fs.mkdir(output, { recursive: true });
const fonts = [
  { file: 'hanken-grotesk-latin.woff2', css: 'family=Hanken+Grotesk:wght@400..800', license: 'https://raw.githubusercontent.com/google/fonts/main/ofl/hankengrotesk/OFL.txt', licenseFile: 'Hanken-Grotesk-OFL.txt' },
  { file: 'jetbrains-mono-latin.woff2', css: 'family=JetBrains+Mono:wght@400..700', license: 'https://raw.githubusercontent.com/google/fonts/main/ofl/jetbrainsmono/OFL.txt', licenseFile: 'JetBrains-Mono-OFL.txt' },
  { file: 'material-symbols.woff2', css: `family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&icon_names=${iconNames.join(',')}`, license: 'https://raw.githubusercontent.com/google/material-design-icons/master/LICENSE', licenseFile: 'Material-Symbols-LICENSE.txt' },
];
const styles = [], metadata = [];
for (const font of fonts) {
  const cssUrl = `https://fonts.googleapis.com/css2?${font.css}&display=block`;
  const css = await (await get(cssUrl)).text();
  const face = font.file.includes('material') ? css.match(/@font-face\s*\{[^}]+\}/)?.[0]
    : css.match(/\/\* latin \*\/\s*(@font-face\s*\{[^}]+\})/)?.[1];
  const source = face?.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/)?.[1];
  if (!source) throw new Error(`No WOFF2 font found for ${font.file}: ${css}`);
  const bytes = Buffer.from(await (await get(source)).arrayBuffer());
  if (bytes.subarray(0, 4).toString() !== 'wOF2') throw new Error(`Invalid WOFF2 for ${font.file}`);
  await fs.writeFile(path.join(output, font.file), bytes);
  await fs.writeFile(path.join(output, font.licenseFile), (await (await get(font.license)).text()).replace(/[ \t]+$/gm, ''));
  styles.push(face.replace(/url\([^)]+\)/, `url('/fonts/${font.file}')`));
  metadata.push({ file: font.file, bytes: bytes.length, source, cssUrl, license: font.license });
}
await fs.mkdir(path.join(root, 'src', 'assets'), { recursive: true });
await fs.writeFile(path.join(root, 'src', 'assets', 'fonts.css'), `/* Generated by scripts/vendor-fonts.mjs. Licenses in public/fonts. */\n${styles.join('\n\n')}\n`);
await fs.writeFile(path.join(output, 'manifest.json'), `${JSON.stringify({ iconNames, fonts: metadata }, null, 2)}\n`);
console.log(`Vendored ${iconNames.length} icons; ${metadata.reduce((sum, font) => sum + font.bytes, 0)} font bytes.`);
